=== MERADABDERRAZZAK/XML/students.dtd
<!ELEMENT Faculty (Student*)>

<!ELEMENT Student (FirstName, FamilyName, Age, Address?, Level, Speciality, Average)>
<!ATTLIST Student RegistrationNumber CDATA #REQUIRED>

<!ELEMENT FirstName  (#PCDATA)>
<!ELEMENT FamilyName (#PCDATA)>
<!ELEMENT Age        (#PCDATA)>
<!ELEMENT Address    (Number, City, PostalCode)>
<!ELEMENT Level      (#PCDATA)>
<!ELEMENT Speciality (#PCDATA)>
<!ELEMENT Average    (#PCDATA)>

<!ELEMENT Number     (#PCDATA)>
<!ELEMENT City       (#PCDATA)>
<!ELEMENT PostalCode (#PCDATA)>

=== MERADABDERRAZZAK/XML/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Faculty SYSTEM "students.dtd">

<Faculty>

  <Student RegistrationNumber="39414409">
    <FirstName>Abd errazzak</FirstName>
    <FamilyName>Merad</FamilyName>
    <Age>21</Age>
    <Address>
      <Number>46</Number>
      <City>Mih Ouensa</City>
      <PostalCode>39030</PostalCode>
    </Address>
    <Level>3L</Level>
    <Speciality>ComputerScience</Speciality>
    <Average>0.00</Average>
  </Student>

</Faculty>
